# Generated by Django 5.0.7 on 2024-07-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_employee_monthly_blockers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Blocker', 'Blocker'), ('Major', 'Major'), ('Minor', 'Minor')], default='Minor', max_length=10),
        ),
    ]
