# Generated by Django 5.0.7 on 2024-07-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.team'),
        ),
    ]
